package io.github.pmalirz.dlock.core.expiration;

import io.github.pmalirz.dlock.core.model.ReadLockRecord;

/**
 * Expires the lock when createdTime + expirationSeconds > NOW.
 * The NOW is provided by the lock itself (generated by the central repository,
 * e.g. DB).
 */
public class LocalLockExpirationPolicy implements LockExpirationPolicy {

    @Override
    public boolean expired(ReadLockRecord readLockRecord) {
        return readLockRecord.createdTime()
                .plusSeconds(readLockRecord.expirationSeconds())
                .isBefore(readLockRecord.currentTime());
    }

}
